language: haskell

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

services:
  - docker

install:
  - >
    curl --fail --location --show-error --silent https://get.haskellstack.org
    | sh
  - stack --version

script:
  - ci/build.sh
