language: haskell

cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work

services:
  - docker

install:
  - wget --output-document - https://get.haskellstack.org | sh
  - stack --version

script:
  - scripts/build.sh
