name: buffet
version: 0.1.0
github: evolutics/buffet
license: MIT
author: Benjamin Fischer
maintainer: benjamin.fischer@evolutics.info
copyright: 2019 Benjamin Fischer
extra-source-files:
  - README.md
synopsis: Assembles many Dockerfiles in one.
category: Development
description: See https://github.com/evolutics/buffet
dependencies:
  - base >= 4.7 && < 5
_ghc-options: &ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror
  - -Weverything
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
internal-libraries:
  buffet-internal:
    source-dirs: src
    ghc-options: *ghc-options
    dependencies:
      - aeson
      - aeson-pretty
      - bytestring
      - cassava
      - containers
      - directory
      - filepath
      - language-docker
      - mustache
      - optparse-applicative
      - parsec
      - random
      - split
      - text
      - typed-process
      - unordered-containers
      - vector
      - yaml
executables:
  buffet-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options
    dependencies:
      - buffet-internal
tests:
  buffet-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: *ghc-options
    dependencies:
      - aeson
      - buffet-internal
      - bytestring
      - directory
      - filepath
      - tasty
      - tasty-hunit
      - text
      - typed-process
      - unordered-containers
      - vector
      - yaml
