name: buffet
version: 1.0.1
github: evolutics/buffet
license: MIT
author: Benjamin Fischer
maintainer: benjamin.fischer@evolutics.info
copyright: 2019 Benjamin Fischer
extra-source-files:
  - README.md
synopsis: Assembles many Dockerfiles in one
category: Development
description: See https://github.com/evolutics/buffet
dependencies:
  - base >= 4.7 && < 5
_ghc-options-executable: &ghc-options-executable
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-local-signatures
  - -Wno-safe
  - -Wno-unsafe
_ghc-options-library: &ghc-options-library
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-deriving-strategies
  - -Wno-missing-local-signatures
  - -Wno-safe
  - -Wno-unsafe
internal-libraries:
  buffet-internal:
    source-dirs: src
    ghc-options: *ghc-options-library
    dependencies:
      - aeson
      - aeson-pretty
      - bytestring
      - cassava
      - containers
      - directory
      - filepath
      - language-docker
      - mustache
      - optparse-applicative
      - parsec
      - prettyprinter
      - random
      - split
      - text
      - typed-process
      - unordered-containers
      - vector
      - yaml
    generated-other-modules:
      - Paths_buffet
executables:
  buffet:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options-executable
    dependencies:
      - buffet-internal
    generated-other-modules:
      - Paths_buffet
tests:
  buffet-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: *ghc-options-executable
    dependencies:
      - aeson
      - buffet-internal
      - bytestring
      - directory
      - filepath
      - tasty
      - tasty-hunit
      - text
      - typed-process
      - unordered-containers
      - vector
      - yaml
    generated-other-modules:
      - Paths_buffet
