name: buffet
version: "0.1.0.0"
github: "evolutics/buffet"
license: MIT
author: "Benjamin Fischer"
maintainer: "benjamin.fischer@evolutics.info"
copyright: "2019 Benjamin Fischer"
extra-source-files:
  - README.md
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development
# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/evolutics/buffet#readme>
dependencies:
  - base >= 4.7 && < 5
_ghc-options: &ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Werror
  - -Weverything
  - -Wno-unsafe
  - -Wno-safe
internal-libraries:
  buffet-internal:
    source-dirs: src
    ghc-options: *ghc-options
    dependencies:
      - aeson
      - bytestring
      - cassava
      - containers
      - directory
      - filepath
      - language-docker
      - split
      - text
      - typed-process
      - vector
      - yaml
executables:
  buffet-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options
    dependencies:
      - buffet-internal
      - optparse-applicative
      - text
tests:
  buffet-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: *ghc-options
    dependencies:
      - aeson
      - buffet-internal
      - bytestring
      - directory
      - filepath
      - tasty
      - tasty-golden
      - tasty-hunit
      - text
