FROM alpine
LABEL org.opencontainers.image.title='Foo'
LABEL org.opencontainers.image.url='https://example.com/foo'
LABEL org.opencontainers.image.authors='Boo Far,Baz'
LABEL org.opencontainers.image.version='1.2.3'
