#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  docker build \
    --build-arg "buffet_version=${DOCKER_TAG}" \
    --file "${DOCKERFILE_PATH}" \
    --tag "${IMAGE_NAME}" \
    .
}

main "$@"
