#!/bin/bash

set -o errexit -o nounset -o pipefail

main() {
  local -r latest_image="${DOCKER_REPO}:latest"
  docker tag "${IMAGE_NAME}" "${latest_image}"
  docker push "${latest_image}"
}

main "$@"
