FROM alpine
ARG git

LABEL org.opencontainers.image.title="Git"
LABEL org.opencontainers.image.url="https://git-scm.com"
LABEL info.evolutics.freezer.help="git --help"

RUN apk add --no-cache "git==${git}"
