- arguments: [--color]
- extensions:
    - default: false
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- modules:
    - { name: [Data.HashMap, Data.Map, Data.Map.Strict], as: Map }
    - { name: [Data.HashSet, Data.Set, Data.Set.Strict], as: Set }
- group:
    name: base
    enabled: true
    imports:
      - package base
    rules:
      - warn: { lhs: mapM, rhs: traverse }
      - warn: { lhs: return, rhs: pure }
      - warn: { lhs: sequence, rhs: sequenceA }
- group:
    name: text
    enabled: true
    rules:
      - warn: { lhs: Data.Text.concat, rhs: mconcat }
